version: '3.5'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
    - "9200:9200"
    - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    labels:
      com.dnsdock.image: "kibana"
      com.dnsdock.region: "mintel"
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch

  configurator:
    image: mintel/docker-alpine-bash-curl-jq:2.2.0
    environment:
      HOME: /tmp
      ES_ENDPOINT: http://elasticsearch:9200
      KIBANA_ENDPOINT: http://kibana:5601
    entrypoint:
    - dockerize
    - "-wait"
    - ${KIBANA_ENDPOINT}
    - "-wait"
    - ${ES_ENDPOINT}/_cluster/health
    - "-timeout"
    - 600s
    - -wait-retry-interval
    - 30s
    - -insecure-ssl
    - "--"
    - bash
    - /tmp/configurator.sh
    volumes:
    - "./configurator.sh:/tmp/configurator.sh"
